const fullnames: Record<string,string>  = {
    "memphis": "Memphis Grizzlies",
    "boston": "Boston Celtics",
    "new orleans": "New Orleans Pelicans",
    "new york": "New York Knicks",
    "philadelphia": "Philadelphia 76ers",
    "toronto": "Toronto Raptors",
    "chicago": "Chicago Bulls",
    "cleveland": "Cleveland Cavaliers",
    "detroit": "Detroit Pistons",
    "indiana": "Indiana Pacers",
    "milwaukee": "Milwaukee Bucks",
    "atlanta": "Atlanta Hawks",
    "charlotte": "Charlotte Hornets",
    "miami": "Miami Heat",
    "orlando": "Orlando Magic",
    "washington": "Washington Wizards",
    "denver": "Denver Nuggets",
    "minnesota": "Minnesota Timberwolves",
    "oklahoma": "Oklahoma City Thunder",
    "portland": "Portland Trail Blazers",
    "san antonio": "San Antonio Spurs",
    "utah": "Utah Jazz",
    "dallas": "Dallas Mavericks",
    "golden state": "Golden State Warriors",
    "houston": "Houston Rockets",
    "l.a. clippers": "Los Angeles Clippers",
    "l.a. lakers": "Los Angeles Lakers",
    "phoenix": "Phoenix Suns",
    "sacramento": "Sacramento Kings",
    "golden st.": "Golden State Warriors",
    "oklahoma city": "Oklahoma City Thunder",
    "brooklyn": "Brooklyn Nets"
}

export default fullnames;