const logos: Record<string,string> = {
    "Atlanta": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/atl.png",
    "Boston": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bos.png",
    "New Orleans Pelicans": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/no.png",
    "Chicago Bulls": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/chi.png",
    "Cleveland Cavaliers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cle.png",
    "Dallas Mavericks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/dal.png",
    "Denver Nuggets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/den.png",
    "Detroit Pistons": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/det.png",
    "Golden State Warriors": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/gs.png",
    "Houston Rockets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/hou.png",
    "Indiana Pacers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ind.png",
    "LA Clippers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/lac.png",
    "LA Lakers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/lal.png",
    "Miami Heat": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mia.png",
    "Milwaukee Bucks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mil.png",
    "Minnesota Timberwolves": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/min.png",
    "Brooklyn Nets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/bkn.png",
    "New York Knicks": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/ny.png",
    "Orlando Magic": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/orl.png",
    "Philadelphia 76ers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/phi.png",
    "Phoenix Suns": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/pho.png",
    "Portland Trail Blazers": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/por.png",
    "Sacramento Kings": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/sac.png",
    "San Antonio Spurs": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/sas.png",
    "Oklahoma City Thunder": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/okc.png",
    "Toronto Raptors": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/tor.png",
    "Utah Jazz": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/utah.png",
    "Memphis Grizzlies": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/mem.png",
    "Washington Wizards": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/was.png",
    "Charlotte Hornets": "https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/cha.png"
}

export default logos;